version: "3.11"

services:
  burger_postgres:
    image: postgres:14
    container_name: burger_postgres
    volumes:
      - ~/.pg/pg_data/starburger:/var/lib/postgresql/data
    env_file:
      - .env

  starburger:
    image: burger_django:latest
    container_name: burger_django
    depends_on:
      - burger_postgres
    volumes:
      - static_volume:/starburger/static
      - media_volume:/starburger/media
    env_file:
      - .env
    command: >
      bash -c "./manage.py collectstatic --noinput && ./manage.py migrate && gunicorn -b 0.0.0.0:8000 star_burger.wsgi:application"
      
  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./docker/nginx
    container_name: starburger_nginx
    image: starburger_nginx
    volumes:
      - static_volume:/starburger/static
      - media_volume:/starburger/media
    depends_on:
      - burger_project
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"

volumes:
  static_volume:
  media_volume:
