# Generated by Django 3.2.15 on 2023-08-05 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_auto_20230802_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Необработанный'), ('cooking', 'Готовится'), ('delivery', 'Доставка'), ('ready', 'Доставлен')], db_index=True, default='new', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
