# Generated by Django 3.2.15 on 2023-08-05 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_auto_20230805_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay',
            field=models.CharField(choices=[('CASH', 'Наличными'), ('ELECTRON', 'Электронно')], db_index=True, default=1, max_length=20, verbose_name='Способ оплаты'),
            preserve_default=False,
        ),
    ]
