# Generated by Django 4.2.4 on 2023-08-30 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_alter_orderitem_price_alter_orderitem_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='phone_number',
            new_name='phonenumber',
        ),
    ]
